## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np

In [5]:
arr = np.array([[17,21,31],[21,52,45],[8,55,1]])
arr2 = np.array([[11,32,52],[15,1,43],[61,3,23]])

In [6]:
arr * arr2

array([[ 187,  672, 1612],
       [ 315,   52, 1935],
       [ 488,  165,   23]])

## Write a NumPy program to compute the determinant of a given square array

In [7]:
arr = np.array([[15,21,22], [31,24,55],[18,2,20]]) 
np.linalg.det(arr)

5179.9999999999945

## Write a NumPy program to compute the cross product of two given vectors

In [8]:
arr = np.array([15,21,38])
arr2 = np.array([86,52,41])

In [9]:
np.cross(arr,arr2)

array([-1115,  2653, -1026])

## Write a NumPy program to compute the condition number of a given matrix

In [10]:
arr = np.array([[17,21,31],[21,52,45],[8,55,1]])

In [11]:
np.linalg.cond(arr)

27.183581682589725

## Write a NumPy program to compute the inverse of a given matrix

In [12]:
arr = np.array([[11,32,52],[15,1,43],[61,3,23]])

In [13]:
np.linalg.inv(arr)

array([[-0.00149511, -0.00818077,  0.01867472],
       [ 0.03213067, -0.04117182,  0.00433016],
       [-0.00022568,  0.02706705, -0.00661514]])